version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: sls-migrate-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sls_migrate
      MYSQL_USER: sls_user
      MYSQL_PASSWORD: sls_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - sls-network

  # SLS Migrate 应用
  app:
    build: .
    container_name: sls-migrate-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - GIN_MODE=release
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=sls_user
      - DB_PASSWORD=sls_pass
      - DB_DATABASE=sls_migrate
      - DB_CHARSET=utf8mb4
      - DB_MAX_IDLE_CONNS=10
      - DB_MAX_OPEN_CONNS=100
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sls-network

  # phpMyAdmin (可选，用于数据库管理)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sls-migrate-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: sls_user
      PMA_PASSWORD: sls_pass
    depends_on:
      - mysql
    networks:
      - sls-network

volumes:
  mysql_data:

networks:
  sls-network:
    driver: bridge
